[package]
name = "epoxy-server"
version = "2.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.1"
fastwebsockets = { version = "0.8.0", features = ["unstable-split", "upgrade"] }
futures-util = "0.3.30"
http-body-util = "0.1.2"
hyper = { version = "1.4.1", features = ["server", "http1"] }
hyper-util = { version = "0.1.6", features = ["tokio"] }
lazy_static = "1.5.0"
regex = "1.10.5"
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.38.1", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["compat", "io-util", "net"] }
toml = "0.8.15"
wisp-mux = { version = "5.0.0", path = "../wisp", features = ["fastwebsockets"] }
